routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('logout', 'UserController@logout');

Route::resource('ratings', 'RatingController');

Route::get('mission', 'LandingController@mission')->name('mission');

Route::get('personnel', 'LandingController@personnel')->name('personnel');

Route::get('rating', 'LandingController@rating')->name('rating');

Route::get('/', 'LandingController@index');

Route::get('advertises/{advertise}', 'LandingController@advertiseSingle');

Route::get('post/{post}', 'LandingController@postSingle');

Route::any('allpost', 'LandingController@postAll');

Route::any('advertises', 'LandingController@advertises');

Route::get('download/{id}', 'LandingController@download')->name('downloadDoc');

Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/', 'PostController@all');
Route::get('/posts/{post}', 'PostController@single');

Route::get('/admin/{any}', 'AdminController@index')->where('any', '.*');

Route::get('/center/{any}', 'AdminController@center')->where('any', '.*');

Route::get('/officer/{any}', 'AdminController@officer')->where('any', '.*');

Route::get('/inventories/{any}', 'AdminController@inventories')->where('any', '.*');

Route::get('pdf', 'LandingController@pdf');

Route::get('repairs/printable/{id}', 'RepairController@printable');

Route::any('finditem', 'LandingController@itemFind');

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
  protected $fillable = [
    // 'name',
    // 'type',
    // 'other_type',
    'problem',
    // 'status',
    // 'attach',
    'description',
    'item_type_id'
  ];

  public function flies()
  {
    return $this->morphMany('App\Fly', 'fileable');
  }

  public function repair()
  {
    return $this->belongsTo(Repair::class);
  }

  public function item_type()
  {
    return $this->belongsTo(ItemType::class);
  }

  public function getTypeNameAttribute()
  {
    $name = [
      'vehicle' => 'ยานพาหนะ',
      'electronics' => 'เครื่องใช้ไฟฟ้า/เครื่องใช้ในครัวเรือน',
      'machine' => 'เครื่องมือเครื่องจักรการเกษตร',
      'other' => 'อื่นๆ'
    ];

    return $name[$this->type];
  }
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;

class Post extends Model
{
  protected $fillable = ['title', 'description', 'type'];

  public function scopeAdvertise($query)
  {
    return $query->where('type', 'advertise');
  }

  public function scopeActivities($query)
  {
    return $query->where('type', 'activities');
  }

  public function scopeInformation($query)
  {
    return $query->where('type', 'information');
  }

  public function flies()
  {
    return $this->morphMany('App\Fly', 'fileable');
  }

  public function getFilePathAttribute()
  {
    return 'upload/posts/';
  }

  public function getTypeNameAttribute()
  {
    $name = [
      'advertise' => 'ข่าวประชาสัมพันธ์',
      'activities' => 'ภาพกิจกรรม',
      'information' => 'บริการข้อมูล'
    ];

    return $name[$this->type];
  }

  public function getPublicPathAttribute()
  {
    return getPublicPathPost();
  }

  public function delete()
  {
    $fileID = $this->flies->map(function($item, $key) {
        return $item->id;
    });

    \App\Fly::destroy($fileID);


    return parent::delete();
  }

}

app/Repair.php
<?php

namespace App;

use App\SparePart;
use App\Http\Resources\SparePartResource;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;

class Repair extends Model
{
  protected $fillable = [
    'center_id',
    'citizen_id',
    'cost',
    'description',
    'start_date',
    'end_date',
    'result',
    'forward',
    'receiver_name',
    'receiver_date',
    'sender_name',
    'sender_date',
    'citizen_review',
    'citizen_comment',
    'technician_review',
    'technician_comment',
    'finished'
  ];

  public function center()
  {
    return $this->belongsTo(Center::class);
  }

  public function citizen()
  {
    return $this->belongsTo(Citizen::class);
  }

  public function item()
  {
    return $this->hasOne(Item::class);
  }

  public function performer()
  {
    return $this->hasOne(Performer::class);
  }

  public function inventories()
  {
    return $this->morphMany(Inventory::class, 'inventoriable');
  }

  public function getInventoriesCollectAttribute()
  {
    $inventories = $this->inventories->groupBy('spare_part_id');
    $parts = collect([]);

    foreach ($inventories as $key => $value) {
      $part = SparePart::find($key);
      $parts->push([
        'part' => new SparePartResource($part),
        'cost' => $value->sum('cost')
      ]);
    }

    return $parts;
  }

  public function scopeWaitRepair($query)
  {
    $query = $query->has('item');
    return $query->where('result', 'wait')->where('finished', false);
  }

  public function scopeWaitSendback($query)
  {
    $query = $query->has('item');
    return $query->whereNotIn('result', ['wait'])->where('finished', false);
  }

  public function scopeFinished($query)
  {
    $query = $query->has('item');
    return $query->where('finished', true);
  }

  public function scopeNotWait($query)
  {
    $query = $query->has('item');
    return $query->whereNotIn('result', ['wait']);
  }

  public function getResultNameAttribute()
  {
    $name = [
      'wait' => 'รอซ่อม',
      'reparable' => 'ซ่อมได้',
      'irreparable' => 'ซ่อมไม่ได้',
      'forward' => 'ส่งซ่อมต่อ' . ' ' . $this->forward
    ];

    return $name[$this->result];
  }

  public function getStatusAttribute()
  {
    if ($this->result == 'wait' and $this->finished == false) return 'waitrepair';
    if ($this->result !== 'wait' and $this->finished == false) return 'waitsendback';
    if ($this->result !== 'wait' and $this->finished) return 'finished';

    return 'waitrepair';
  }

  public function getResultAttribute($value)
  {
    return $value ? $value : '';
  }

  public function getDescriptionAttribute($value)
  {
    return $value ? $value : '';
  }

  public function getForwardAttribute($value)
  {
    return $value ? $value : '';
  }

  public function getCitizenReviewAttribute($value)
  {
    return $value ? $value : '';
  }

  public function getTechnicianReviewAttribute($value)
  {
    return $value ? $value : '';
  }

  public function getCitizenCommentAttribute($value)
  {
    return $value ? $value : '';
  }

  public function getTechnicianCommentAttribute($value)
  {
    return $value ? $value : '';
  }

  public function getSenderNameAttribute($value)
  {
    return $value ? $value : '';
  }

  public function getReceiverNameAttribute($value)
  {
    return $value ? $value : '';
  }

  public function part_save($parts)
  {
    $inventories = $this->inventories;
    if ($inventories->count() == 0) $this->addNewInventories($parts);
    else $this->addInventories($parts);
  }

  public function partCollect($parts)
  {
    $id = collect([]);
    foreach ($parts as $part) { $id->put($part['part']['id'], $part['cost']); }
    return $id;
  }

  public function changePart($old, $new, $keys)
  {
    foreach ($keys as $key) {
      $oldCost = abs($old->get($key));
      $newCost = $new->get($key);
      $diffCost = $oldCost - $newCost;
      if ($diffCost == 0) continue;
      $this->newInventory($key, $diffCost);
    }
  }

  public function deletePart($old, $keys)
  {
    foreach ($keys as $key => $value) {
      $cost = abs($old->get($key));
      $this->newInventory($key, $cost);
    }
  }

  public function addPart($new, $keys)
  {
    foreach ($keys as $key => $value) {
      $cost = $new->get($key) * -1;
      $this->newInventory($key, $cost);
    }
  }

  public function addInventories($parts)
  {
    $oldPart = $this->partCollect($this->inventories_collect);
    $newPart = $this->partCollect($parts);
    $intersectPart = $oldPart->intersectByKeys($newPart);
    $intersectKeys = $intersectPart->keys()->all();
    $delPart = $oldPart->except($intersectKeys)->all();
    $addPart = $newPart->except($intersectKeys)->all();

    if ($intersectPart->isNotEmpty()) $this->changePart($oldPart, $newPart, $intersectKeys);
    if (!empty($delPart)) $this->deletePart($oldPart, $delPart);
    if (!empty($addPart)) $this->addPart($newPart, $addPart);
  }

  public function addNewInventories($parts)
  {
    foreach ($parts as $part) {
      $id = $part['part']['id'];
      $cost = $part['cost'] * -1;
      $this->newInventory($id, $cost);
    }
  }

  public function newInventory($partId, $cost)
  {
    $part = SparePart::find($partId);
    $balance = $part->balance + $cost;

    $inventory = new Inventory;
    $inventory->spare_part_id = $part->id;
    $inventory->cost = $cost;
    $inventory->balance = $balance;

    $this->inventories()->save($inventory);
  }

}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/item_find.blade.php
@extends('layouts.landing')

@section('title', 'ของซ่อม')

@section('content')
  <div class="row mt-3 pb-3">
    <div class="col"></div>
    <div class="col-12 col-lg-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">บริการข้อมูลของซ่อม</h5>
          <h6 class="card-title">ชื่อศูนย์: {{ $repair->center->name }}</h5>
          <p class="card-text">
            ชื่อ-สกุล: {{ $repair->citizen->fullname }}
          </p>
          <p class="card-text">
            สิ่งของที่นำซ่อม: {{ $repair->item->item_type->name }}
          </p>
          <p class="card-text">
            อาการเสีย: {{ $repair->item->problem }}
          </p>
          <p class="card-text">
            รายละเอียด: {{ $repair->item->description }}
          </p>
          <p class="card-text">
            ผลการซ่อม: {{ $repair->result_name }}
          </p>
          <p class="card-text">
            รายละเอียดการซ่อม: {{ $repair->description }}
          </p>
          @foreach ($repair->item->flies()->photo()->get() as $photo)
            <img src="{!! '/upload/items/' . $photo->destination !!}" width="200" height="200" />
          @endforeach
        </div>
      </div>

    </div>
    <div class="col"></div>

  </div>
@endsection

resources/views/mission.blade.php
@extends('layouts.landing')

@section('title', 'หน้าที่และความรับผิดชอบ')

@section('content')
  <div class="row mt-3 pb-3">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
      <div class="card shadow">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">หน้าที่และความรับผิดชอบ</h6>
        </div>
        <div class="card-body">
          {!! $mission->content !!}
        </div>
      </div>
    </div>
  </div>
@endsection

@section('footer-class')
  <footer class="footer bg-light fixed-bottom">
@endsection

resources/views/pdf.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    {{-- <title>{{ config('app.name', 'Laravel') }}</title> --}}
    <title>Fixitcenter chaiant - @yield('title')</title>

    <!-- Styles -->
    {{-- <link href="{{ asset('css/landing.css') }}" rel="stylesheet"> --}}

    <style lang="css">
      div.card {
        display: inline-block;
        width: 90mm;
        min-height: 60mm;
        max-height: 60mm;
        border: 1px solid black;
      }

      div > span {
        font-size: 10pt;
      }

      div > p {
        font-size: 8pt;
        margin-top: 0;
        margin-left: 5mm;
        line-height: 1;
      }
    </style>
</head>
<body>
  <div class="card">
    <p class="strong"></p>
    <p><strong>{{ $repair->center->name}} เลขที่ใบรับซ่อม </strong> {{ $repair->id }} <strong>วันที่ </strong> {{ $repair->created_at}}</p>
    <p><strong>{{ $repair->citizen->title . ' ' . $repair->citizen->fullname}} เบอร์โทรศัพ {{ $repair->citizen->phoneFormat}}</strong></p>
    <p><strong>สิ่งของที่นำมาซ่อม </strong> {{ $repair->item->name }} <strong>ประเภท</strong> {{ $repair->item->type_name }}</p>
    <p><strong>อาการเสีย</strong> {{ $repair->item->problem}}</p>
    <p><strong>สภาพสินค้า</strong> {{ $repair->item->status}}</p>
    <p><strong>อุปกรณ์ที่ติดมาด้วย</strong> {{ $repair->item->attach}}</p>
    <p><strong>ผลการซ่อม ซ่อมได้ &#9634; ซ่อมไม่ได้ &#9634; ส่งซ่อมต่อ &#9634;</strong>....................................</p>
    <p><strong>ผู้ซ่อม</strong>........................................................................................</p>
    <p><strong>วันที่ซ่อมเสร็จ </strong>.................................................................................</p>
  </div>
  <div class="card">
    <p class="strong"></p>
    <p><strong>{{ $repair->center->name}} เลขที่ใบรับซ่อม </strong> {{ $repair->id }} <strong>วันที่ </strong> {{ $repair->created_at}}</p>
    <p><strong>{{ $repair->citizen->title . ' ' . $repair->citizen->fullname}} เบอร์โทรศัพ {{ $repair->citizen->phoneFormat}}</strong></p>
    <p><strong>สิ่งของที่นำมาซ่อม </strong> {{ $repair->item->name }} <strong>ประเภท</strong> {{ $repair->item->type_name }}</p>
    <p><strong>อาการเสีย</strong> {{ $repair->item->problem}}</p>
    <p><strong>สภาพสินค้า</strong> {{ $repair->item->status}}</p>
    <p><strong>อุปกรณ์ที่ติดมาด้วย</strong> {{ $repair->item->attach}}</p>
    <p><strong>ผลการซ่อม ซ่อมได้ &#9634; ซ่อมไม่ได้ &#9634; ส่งซ่อมต่อ &#9634;</strong>....................................</p>
    <p><strong>ผู้ซ่อม</strong>........................................................................................</p>
    <p><strong>วันที่ซ่อมเสร็จ </strong>.................................................................................</p>
  </div>
  {{-- <div class="container">
    <div class="row">
      <div class="col-md-6 col-xs-6 border border-dark">
        <div class="card">
          <div class="card-body">
            <img class="bg" src="http://www.fixitcenter.org/fixit62/imgschool/null_img.png" />
            <p><strong>ศูนย์ถาวร เลขที่ใบรับซ่อม </strong> 54 <strong>วันที่ </strong> 11 เมษยน 2562</p>
            <p><strong>นาย พํฒนะ ุภูดิสโสภณ เบอร์โทรศัพ 084-1499694</strong></p>
            <p><strong>สิ่งของที่นำมาซ่อม </strong> พัดลม <strong>ประเภท</strong> เครื่องใช้ไฟฟ้า/เครื่องใช้ในครัวเรือน</p>
            <p style="line-height: 1;"><strong>อาการเสีย</strong></p>
            <p style="line-height: 1;"><strong>สภาพสินค้า</strong></p>
            <p style="line-height: 1;"><strong>อุปกรณ์ที่ติดมาด้วย</strong></p>
            <p><strong>ผลการซ่อม ซ่อมได้ &#9634; ซ่อมไม่ได้ &#9634; ส่งซ่อมต่อ &#9634;</strong>....................................</p>
            <p><strong>ผู้ซ่อม</strong>........................................................................................</p>
            <p><strong>วันที่ซ่อมเสร็จ </strong>.................................................................................</p>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-xs-6 border border-dark">
        <div class="card">
          <div class="card-body">
            <img class="bg" src="http://www.fixitcenter.org/fixit62/imgschool/null_img.png" />
            <p><strong>ศูนย์ถาวร เลขที่ใบรับซ่อม </strong> 54 <strong>วันที่ </strong> 11 เมษยน 2562</p>
            <p><strong>นาย พํฒนะ ุภูดิสโสภณ เบอร์โทรศัพ 084-1499694</strong></p>
            <p><strong>สิ่งของที่นำมาซ่อม </strong> พัดลม <strong>ประเภท</strong> เครื่องใช้ไฟฟ้า/เครื่องใช้ในครัวเรือน</p>
            <p style="line-height: 1;"><strong>อาการเสีย</strong></p>
            <p style="line-height: 1;"><strong>สภาพสินค้า</strong></p>
            <p style="line-height: 1;"><strong>อุปกรณ์ที่ติดมาด้วย</strong></p>
            <img class="item" src="https://static.bigc.co.th/media/catalog/product/cache/2/image/497x497/9df78eab33525d08d6e5fb8d27136e95/8/8/8850918004322_1.jpg" />
          </div>
        </div>
      </div>
    </div>

  </div> --}}
  {{-- <script src="{{ asset('js/app.js')}}"></script> --}}
</body>
</html>

resources/views/personnel.blade.php
@extends('layouts.landing')

@section('title', 'บุคลากรงานโครงการพิเศษ')

@section('content')
  <div class="row mt-3 pb-3">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
      <div class="card shadow">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">
            บุคลากรงานโครงการพิเศษ
          </h6>
        </div>
        <div class="card-body">
          {!! $personnel->content !!}
        </div>
      </div>
    </div>
  </div>
@endsection

@section('footer-class')
  <footer class="footer bg-light fixed-bottom">
@endsection

resources/views/post.blade.php
@extends('layouts.landing')

@section('title', 'ข่าวประชาสัมพันธ์')

@section('content')
  <div class="row mt-3 pb-3">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
      <div class="card">
        <div class="card-header text-center">
          {{ $post->type_name }}
        </div>
        <div class="card-body">
          <h6>หัวข้อข่าว : <small class="text-muted"> {{ $post->title}}</small></h6>
          <h6 class="mt-3">รายละเอียดข่าว</h6>
          <div class="ml-3">
            {!! $post->description !!}
          </div>
          <h6 class="mt-3">รูปภาพ</h6>
          <div class="row">
            @foreach ($post->flies()->photo()->get() as $photo)
              <div class="col-lg-3 col-md-3 col-4 pb-2">
                @desktop
                  <img src="{!! '/upload/posts/'.$photo->destination !!}" width="200" height="200" class="rounded border border-dark" />
                @elsedesktop
                  <img src="{!! '/upload/posts/'.$photo->destination !!}" width="100" height="100" class="rounded border border-dark" />
                @enddesktop
              </div>
            @endforeach
          </div>

          <h6 class="mt-3">เอกสาร</h6>
          <div class="row">
            <div class="col-12">
              <table class="table mt-3">
                <thead>
                  <th scope="col">#</th>
                  <th scope="col">name</th>
                  <th scope="col">download</th>
                </thead>
                <tbody>
                  @foreach ($post->flies()->file()->get() as $doc)
                    <tr>
                      <td>{{ $doc->id }}</td>
                      <td>{{ $doc->name }}</td>
                      <td><a href="{{ route('downloadDoc', $doc->id)}}" target="_blank">Download</a></td>
                    </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
@endsection

@section('footer-class')
    <footer class="footer bg-light">
@endsection

resources/views/posts.blade.php
@extends('layouts.landing')

@section('title', 'ข่าวประชาสัมพันธ์ทั้งหมด')

@section('content')
  <div class="row mt-3 pb-3">
    <div class="col-lg-6 offset-lg-3">
      <div class="clearfix">
        <h5 class="float-left"> {{ $postHeader }} </h5>
        <form action="/allpost" method="POST" role="search" class="float-right form-inline">
          {{ csrf_field()}}
          <div class="input-group">
            <select class="custom-select" name="month" id="monthSelect">
              <option selected value="">เลือกเดือน</option>
              @for ($i = 1; $i <= 12; $i++)
                <option
                  value={{$i}}
                  @if ($oldMonth == $i)
                    selected
                  @endif
                >
                  {{ $i }}
                </option>
              @endfor
            </select>
          </div>
          <div class="input-group">
            <select class="custom-select" name="year" id="yearSelect">
              <option selected value="">เลือกปี</option>
              @for ($i = 0; $i <= 10; $i++)
                <option
                  value={{now()->year - $i}}
                  @if ($oldYear == now()->year - $i)
                    selected
                  @endif
                >
                  {{ now()->year - $i }}
                </option>
              @endfor
            </select>
          </div>
          <div class="input-group">
            <input type="text" class="form-control" name="search" placeholder="ค้นหาหัวข้อ" value="{{ $oldSearch }}" />
            <span class="input-group-btn">
              <button type="submit" class="btn btn-primary">
                <i class="fas fa-search"></i>
              </button>
            </span>
          </div>
          <input type="hidden" name="type" value="{{ $type }}"/>
        </form>
      </div>

      <ul class="list-unstyled">
        @foreach ($posts as $post)
          <li class="media my-4">
            <img
              class="mr-3 rounded border border-warning"
              src="{!! !empty($post->flies()->photo()->first()) ? $post->file_path . $post->flies()->photo()->first()->destination : 'http://placehold.it/750x300' !!}"
              width="100"
              height="100"
            />
            <div class="media-body">
              <h5 class="mt-0 mb-1">{{ str_limit($post->title, $limit = 50, $end = '...')}}</h5>
              <p class="card-text">{{ $post->created_at }}</p>
              <a href="/post/{{ $post->id }}" target="_blank">อ่านเพิ่มเติ่ม &rarr;</a>
            </div>
          </li>
        @endforeach
      </ul>

      <div class="text-center">
        {{ $posts->links() }}
      </div>

    </div>
  </div>
@endsection

@section('footer-class')
  <footer class="footer bg-light">
@endsection

resources/views/rating.blade.php
@extends('layouts.landing')

@section('title', 'ความพึงพอใจ')

@section('content')
  @php
    $sex_array = array("1" => "ชาย", "2" => "หญิง");
    $age_array = array(
      "1" => "ต่ำกว่า 18 ปี", "2" => "ระหว่าง 18-23 ปี",
      "3" => "ระหว่าง 24-28 ปี", "4" => "ระหว่าง 29-33 ปี", "5" => "มากกว่า 33 ปี"
    );
    $career_array = array(
      "1" => "เกษตรกร", "2" => "ค้าขาย",
      "3" => "รับจ้างทั่วไป", "4" => "รับราชการ/พนักงานของรัฐ",
      "5" => "พนักงานรัฐวิสาหกิจ", "6" => "พนักงานบริษัท",
      "7" => "อื่นๆ"
    );
    $education_array = array(
      "1" => "ต่ำกว่า ม.3", "2" => "ม.3",
      "3" => "ม.6 / ปวช.", "4" => "ปวส.",
      "5" => "ปริญญาตรี", "6" => "สูงกว่าปริญญาตรี"
    );
    $score_array = array(
      "4" => "มาก", "3" => "ปานกลาง", "2" => "น้อย", "1" => "ปรับปรุง"
    );
    $options_array = array(
      "option1" => "1. ความรู้ /ความสามารถของผู้ให้บริการ",
      "option2" => "2. ความพร้อมของเครื่องมือ/อุปกรณ์ในการให้บริการ",
      "option3" => "3. ระยะเวลาในการให้บริการ",
      "option4" => "4. ประโยชน์ที่ได้รับจากการให้บริการ",
      "option5" => "5. ความสะดวกในการเข้ารับบริการ",
      "option6" => "6. ผู้ให้บริการสามารถนำความรู้ที่ได้รับไปประกอบอาชีพได้",
      "option7" => "7. ผู้ให้บริการมีกริยา วาจา และมารยาทสุภาพ"
    );
  @endphp
  <div class="row mt-3 pb-3">
    <div class="col"></div>
    <div class="col-lg-9 col-sm-10">
      <h4 class="text-center">แบบประเมินความพึงพอใจการดำเนินงาน</h4>
      <h4 class="text-center">ศูนย์ซ่อมสร้างเพื่อชุมชน (Fix it Center) ศูนย์ถาวร</h4>
      <form action="/ratings" method="post">
        {{ csrf_field() }}
        <div class="form-gorup">
          <label>ตอนที่ 1 สภาพทั่วไปของผู้ตอบแบบประเมิน</label>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 col-form-label">เพศ</label>
          <div class="col-sm-9">
            @foreach ($sex_array as $key => $value)
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="sex" value={{$key}} />
                <label class="form-check-label">{{$value}}</label>
              </div>
            @endforeach
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 col-form-label">อายุ</label>
          <div class="col-sm-9">
            @foreach ($age_array as $key => $value)
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="age" value={{$key}} />
                <label class="form-check-label">{{$value}}</label>
              </div>
            @endforeach
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 col-form-label">อาชีพ</label>
          <div class="col-sm-9">
            @foreach ($career_array as $key => $value)
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="career" value={{$key}} />
                <label class="form-check-label">{{$value}}</label>
              </div>
            @endforeach
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 col-form-label">ระดับการศึกษา</label>
          <div class="col-sm-9">
            @foreach ($education_array as $key => $value)
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="education" value={{$key}} />
                <label class="form-check-label">{{$value}}</label>
              </div>
            @endforeach
          </div>
        </div>

        <div class="form-gorup">
          <label>ตอนที่ 2 แบบประเมินความพึงพอใจในการรับบริการ</label>
        </div>

        <table class="table">
          <thead>
            <tr>
              <th scope="col">รายการ</th>
              <th scope="col">มาก</th>
              <th scope="col">ปานกลาง</th>
              <th scope="col">น้อย</th>
              <th scope="col">ปรับปรุง</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($options_array as $key => $value)
              <tr>
                <th scope="row">{{$value}}</th>
                @for ($i = 4; $i > 0; $i--)
                  <td>
                    <input type="radio" name={{$key}} value={{$i}} />
                  </td>
                @endfor
              </tr>
            @endforeach
          </tbody>
        </table>

        <div class="form-group text-center">
          <button type="submit" class="btn btn-primary">ตกลง</button>
        </div>
      </form>
    </div>
    <div class="col"></div>
  </div>
@endsection

@section('footer-class')
  <footer class="footer bg-light">
@endsection