routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('logout', 'UserController@logout');

Route::resource('ratings', 'RatingController');

Route::get('mission', 'LandingController@mission')->name('mission');

Route::get('personnel', 'LandingController@personnel')->name('personnel');

Route::get('rating', 'LandingController@rating')->name('rating');

Route::get('/', 'LandingController@index');

Route::get('advertises/{advertise}', 'LandingController@advertiseSingle');

Route::get('post/{post}', 'LandingController@postSingle');

Route::any('allpost', 'LandingController@postAll');

Route::any('advertises', 'LandingController@advertises');

Route::get('download/{id}', 'LandingController@download')->name('downloadDoc');

Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/', 'PostController@all');
Route::get('/posts/{post}', 'PostController@single');

Route::get('/admin/{any}', 'AdminController@index')->where('any', '.*');

Route::get('/center/{any}', 'AdminController@center')->where('any', '.*');

Route::get('/officer/{any}', 'AdminController@officer')->where('any', '.*');

Route::get('/inventories/{any}', 'AdminController@inventories')->where('any', '.*');

Route::get('pdf', 'LandingController@pdf');

Route::get('repairs/printable/{id}', 'RepairController@printable');

Route::any('finditem', 'LandingController@itemFind');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>


    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Fixit Center Chainat') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                {{-- <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::guard('api')->user()->name }} <span class="caret"></span>
                                </a> --}}

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
</body>
</html>

resources/views/layouts/landing.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    {{-- <title>{{ config('app.name', 'Laravel') }}</title> --}}
    <title>Fixitcenter chaiant - @yield('title')</title>

    <!-- Styles -->
    <link href="{{ asset('css/landing.css') }}" rel="stylesheet">
</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-light bg-orange static-top">
    <div class="container">
      <a class="navbar-brand text-white" href="/">
        <img src="{!! '/images/null_img.png' !!}" width="30" height="30" class="d-inline-block align-top" />
        Fixit Center Chainat
      </a>
      {{-- Authentication Link --}}
      @guest
        <a class="btn btn-primary text-white" href="{{ route('login') }}">เข้าสู่ระบบ</a>
      @else
        <div class="dropdown">
          <button
            class="btn btn-dark dropdown-toggle text-white"
            type="button"
            id="dropdownMenuButton"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false">
            รายการ
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{{ url('center/dashboard')}}">ลงทะเบียน</a>
            <a class="dropdown-item" href=" {{ route('ratings.index')}}">สถิติความพึงพอใจ</a>
            <a class="dropdown-item" href="{{ route('logout')}}">ออกจากระบบ</a>
          </div>
        </div>
      @endguest
      {{-- End of Authentication Link --}}
    </div>
  </nav>
  {{-- End of Navigation --}}
  @yield('content')
  <!-- Footer -->
  {{-- <footer class="footer bg-light fixed-bottom"> --}}
  @yield('footer-class')
    <div class="container">
      <div class="row">
        <div class="col-lg-12 h-100 text-center my-auto">
          <p class="text-muted small mb-4 mb-lg-0">&copy; fixitcenterchainat.com 2019. All Rights Reserved.</p>
        </div>
      </div>
    </div>
  </footer>

  <script src="{{ asset('js/app.js')}}"></script>
  {{-- End of Footer --}}
</body>